image: Visual Studio 2019

assembly_info:
  patch: false

configuration: Release

build_script:
  - ps: dotnet --version
  - ps: dotnet restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /nofetch /b $env:APPVEYOR_REPO_BRANCH
  - ps: dotnet build Usenet.sln --configuration $env:CONFIGURATION --no-restore
  - ps: dotnet test UsenetTests/UsenetTests.csproj --no-build --no-restore
  - ps: dotnet pack Usenet/Usenet.csproj --output . --no-build --no-restore --configuration $env:CONFIGURATION -p:version=$env:GitVersion_NuGetVersion

artifacts:
  - path: '**\Usenet.*nupkg'
    name: UsenetArtifacts
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: kdR0ezKgvtAqExn/40WQ1gKKQ2v3r0UfqgahpsO2jAs=
    server: https://ci.appveyor.com/nuget/keimpema/api/v2/package
    skip_symbols: true
    artifact: UsenetArtifacts
    on:
      APPVEYOR_REPO_TAG: false

  - provider: NuGet
    api_key:
      secure: tNQl2nVGPAKl3OVsWJqpCV1Ad3mGBbSsu2M6hCs1zSJlj9M0wkJykvViJFxiJ5cC
    server: https://www.nuget.org/api/v2/package
    symbol_server: https://www.nuget.org/api/v2/package
    skip_symbols: false
    artifact: UsenetArtifacts
    on:
      APPVEYOR_REPO_TAG: true
